name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "🎉 Welcome to PenTest_Vault! Thank you for taking the time to contribute. Your issue is a step towards improving our project. A member of our team will review it soon. In the meantime, feel free to check out our [CONTRIBUTING.md](https://github.com/phantom0004/PenTest_Vault/blob/main/CONTRIBUTING.md) to get more involved!"
        pr-message: "🚀 Thank you for submitting your first pull request! We are excited to have you contribute to PenTest_Vault. We will review your submission soon and get back to you. Meanwhile, please ensure your PR adheres to our [CONTRIBUTING.md](https://github.com/phantom0004/PenTest_Vault/blob/main/CONTRIBUTING.md) guidelines."
